### ISSUE TITLE
更改item属性时BUG

### ISSUE THREAD

**Issue by chehao1992** [loveway/GCMarqueeView#2]
更改item时，没有把 collectionView 之前得subViews移出。导致叠加显示，内存增长。

**Comment by loveway** [comment]
> 更改item时，没有把 collectionView 之前得subViews移出。导致叠加显示，内存增长。

稍后我看一下哈

**Comment by loveway** [comment]
> 更改item时，没有把 collectionView 之前得subViews移出。导致叠加显示，内存增长。

啥情况关闭了啊，我还没来得及看

**Comment by chehao1992** [comment]
你知道解决就好
